Add repair list command
APDevTeam/Movecraft-Repair pull request #28
Opened 2023-08-07 12:47 UTC by goodroach

2023-08-07 21:07 UTC, TylerS1066 requested changes

2023-08-07 21:07 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            sender.sendMessage(I18nSupport.getInternationalisedString(MOVECRAFT_COMMAND_PREFIX + "RepairList - This command can only be run by a player"));
Console messages aren't supposed to be internationalized.

2023-08-07 21:07 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(I18nSupport.getInternationalisedString(MOVECRAFT_COMMAND_PREFIX + "You don't have permission to use this command."));
You need to either use a pre-existing internationalization string, or create a new one.

2023-08-07 21:07 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(I18nSupport.getInternationalisedString(MOVECRAFT_COMMAND_PREFIX + "Repair States - None Found"));
Same here

2023-08-07 21:07 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +        TopicPaginator pageinator = new TopicPaginator(I18nSupport.getInternationalisedString("Repair States"));
Here

2023-08-07 21:07 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +                player.sendMessage(MOVECRAFT_COMMAND_PREFIX + I18nSupport.getInternationalisedString("Paginator - Invalid Page") +" \"" + args[0] + "\"");
Here, though this one may want to use Movecraft's internationalization instead.

2023-08-07 21:07 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(I18nSupport.getInternationalisedString("Error - Page number out of range."));
Here, though this one may want to use Movecraft's internationalization instead.

2023-08-07 21:07 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(MOVECRAFT_COMMAND_PREFIX + I18nSupport.getInternationalisedString("Repair States - None Found"));
Here

2023-08-07 21:07 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(MOVECRAFT_COMMAND_PREFIX + I18nSupport.getInternationalisedString("Paginator - Invalid page") + "\"" + page + "\"");
Here

2023-08-07 21:13 UTC, TylerS1066 requested changes

2023-08-07 21:13 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +    private int ENTRIES_PER_PAGE = 10;
This is unneeded

2023-08-07 21:13 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +        int totalPages = (int) Math.ceil((double) schemList.length / ENTRIES_PER_PAGE);
The paginator should handle this

2023-08-07 21:13 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +        if (page < 1 || page > totalPages) {
I believe the paginator will handle this as well

2023-08-07 21:13 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +        int endIndex = Math.min(startIndex + ENTRIES_PER_PAGE, schemList.length);
More items here that are handled by the paginator

2023-08-07 21:13 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            pageinator.addLine(schemList[i].getName().replace(".schem", ""));
We should reference the `WEUtils.SCHEMATIC_FORMAT` to get this extension.

2023-08-19 14:38 UTC, TylerS1066 requested changes

2023-08-19 14:38 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            sender.sendMessage("Repair - Must Be Player");
This message shouldn't be the key format for internationalization.  In addition, we should return after sending it.

2023-08-19 14:38 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(I18nSupport.getInternationalisedString(MOVECRAFT_COMMAND_PREFIX + "Insufficient Permissions"));
The command prefix will need to be in front of the internationalization call.

2023-08-19 14:38 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(I18nSupport.getInternationalisedString(MOVECRAFT_COMMAND_PREFIX + "Repair - None Found"));
Same here

2023-08-19 14:38 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(I18nSupport.getInternationalisedString(MOVECRAFT_COMMAND_PREFIX + "Insufficient Permissions"));
In addition, this should reference the Movecraft's internationalization, not Movecraft-Repair's

2023-09-05 19:40 UTC, goodroach commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(I18nSupport.getInternationalisedString("Error - Page number out of range."));
How do I do that exactly? Would it just reference the movecraft instance's I18nSupport class?

2023-09-05 21:44 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            player.sendMessage(I18nSupport.getInternationalisedString("Error - Page number out of range."));
Yup, you can reference the two classes of the same name by specifying the full package and class name, for example:
```java
        int totalPages = (int) Math.ceil((double) schemList.length / ENTRIES_PER_PAGE);

        if (page < 1 || page > totalPages) {
            player.sendMessage(net.countercraft.movecraft.localisation.I18nSupport.getInternationalisedString("Error - Page number out of range."));
```

2023-10-18 13:14 UTC, goodroach commented
I updated this PR implementing all changes requested.

2023-10-18 13:26 UTC, TylerS1066 commented on src/main/resources/localisation/mc-repairlang_en.properties
> +Repair\ -\ Out\ of\ Bounds=Page specified is not within bounds.
Can we use Movecraft's built in string for this?

2023-10-18 18:37 UTC, goodroach commented on src/main/resources/localisation/mc-repairlang_en.properties
> +Repair\ -\ Out\ of\ Bounds=Page specified is not within bounds.
As far as I know, the movecraft strings are either highly specific to a certain function or the string is used for something else so it doesn't make sense in this context.

2023-10-20 13:22 UTC, TylerS1066 commented on src/main/resources/localisation/mc-repairlang_en.properties
> +Repair\ -\ Out\ of\ Bounds=Page specified is not within bounds.
I was specifically referring to line 16, not sure why GitHub highlighted all 4.

I assumed the paginator already had a string for out of bounds in Movecraft, so we can just re-use it.

2023-10-20 13:24 UTC, TylerS1066 commented on src/main/resources/localisation/mc-repairlang_en.properties
> +Repair\ -\ Out\ of\ Bounds=Page specified is not within bounds.
Looks like it does: https://github.com/APDevTeam/Movecraft/blob/aa33964aea62eb7005df6a39adac1d098bfb13ae/modules/Movecraft/src/main/java/net/countercraft/movecraft/util/TopicPaginator.java#L39

2023-10-20 18:39 UTC, goodroach commented on src/main/resources/localisation/mc-repairlang_en.properties
> +Repair\ -\ Out\ of\ Bounds=Page specified is not within bounds.
fixed

2023-10-21 14:52 UTC, TylerS1066 approved these changes

2023-10-21 15:20 UTC, TylerS1066 requested changes

2023-10-21 15:20 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/RepairListCommand.java
> +            pageinator.addLine(schemFile.getName().replace("." + SCHEMATIC_FORMAT.getPrimaryFileExtension(), ""));
Interesting bug I ran into, this will replace `1.schematic` with `1atic`.

We should instead check if the schem name ends with the primary extension, and if so replace it, otherwise just place the full name.

2023-10-21 15:29 UTC, TylerS1066 approved these changes

2023-10-21 15:29 UTC, merged