Fixes/add #17
APDevTeam/Movecraft-Repair pull request #44
Opened 2024-07-31 17:57 UTC by Intybyte

Didn't test but this should do to fix the issue, this is also my first time working on Movecraft-Repair, I hope everything makes sense.

Added a config line for a list of materials to blacklist, this defaults to `bedrock` and `barrier` blocks, this `Set` is checked to make sure that those block types aren't saved in the schematics.

2024-08-02 00:47 UTC, TylerS1066 requested changes

2024-08-02 00:47 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/types/RepairState.java
> +                        if (requiredMaterial.isAir() || Config.RepairBlackList.contains(requiredMaterial))
This will not allow repairing in of materials on the blacklist into inventories, is this intended?

2024-08-02 00:47 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/util/WarfareUtils.java
> +                    if (Config.RepairBlackList.contains(material))
Warfare repair should not be affected by the blacklist.

2024-08-02 07:52 UTC, Intybyte commented on src/main/java/net/countercraft/movecraft/repair/types/RepairState.java
> +                        if (requiredMaterial.isAir() || Config.RepairBlackList.contains(requiredMaterial))
The idea was that if they have some items they shouldn't have in the first place they would not get regenerated, maybe it is best to implement another type of blacklist for that

2024-08-02 07:53 UTC, Intybyte commented on src/main/java/net/countercraft/movecraft/repair/util/WarfareUtils.java
> +                    if (Config.RepairBlackList.contains(material))
Alright reverting those changes

2024-08-03 13:36 UTC, TylerS1066 approved these changes

2024-08-03 14:33 UTC, TylerS1066 requested changes

2024-08-03 14:33 UTC, TylerS1066 commented on src/main/java/net/countercraft/movecraft/repair/types/RepairState.java
> +                        if (requiredMaterial.isAir() || Config.RepairBlackList.contains(requiredMaterial))
This function does not seem to function, and I'm not sure why.

2024-08-03 17:43 UTC, Intybyte commented on src/main/java/net/countercraft/movecraft/repair/types/RepairState.java
> +                        if (requiredMaterial.isAir() || Config.RepairBlackList.contains(requiredMaterial))
Might be because `addInventoryTasks` uses the `inventoryRepair` as it is, it is not like it is filtering them out from `inventoryRepair` after all, gonna do a commit and see if that was the issue

2024-08-04 14:07 UTC, TylerS1066 approved these changes

2024-08-04 14:08 UTC, merged