WorldEdit 7 compatibility
APDevTeam/Movecraft-Repair pull request #6
Opened 2021-03-05 17:01 UTC by eirikh1996

Adding WE 7 compatibility

2021-03-05 17:36 UTC, TylerS1066 requested changes
Has this been tested to still work on WE6 with my PR to APDevTeam Movecraft and Movecraft-Warfare?

2021-03-05 17:36 UTC, TylerS1066 commented on WE6/src/main/java/net/countercraft/movecraft/repair/utils/WE6Utils.java
> +    public Pair<LinkedList<UpdateCommand>, LinkedList<UpdateCommand>> getUpdatCommands(Clipboard clipboard, World world, ArrayDeque<Pair<MovecraftLocation, MovecraftLocation>> locMissingBlocks) {
This should be getUpdateCommands.  We should also define a data structure instead of a pair of linked lists.

2021-03-05 17:36 UTC, TylerS1066 commented on WE7/src/main/java/net/countercraft/movecraft/repair/utils/WE7Utils.java
> +    public Pair<LinkedList<UpdateCommand>, LinkedList<UpdateCommand>> getUpdatCommands(Clipboard clipboard, World world, ArrayDeque<Pair<MovecraftLocation, MovecraftLocation>> locMissingBlocks) {
Same as WE6Utils.

2021-03-05 17:36 UTC, TylerS1066 commented on api/src/main/java/net/countercraft/movecraft/repair/utils/WEUtils.java
> +    public abstract Pair<LinkedList<UpdateCommand>, LinkedList<UpdateCommand>> getUpdatCommands(Clipboard clipboard, World world, ArrayDeque<Pair<MovecraftLocation, MovecraftLocation>> locMissingBloc
Same as WE6 and WE7 utils.

2021-03-05 17:36 UTC, TylerS1066 commented on api/src/main/java/net/countercraft/movecraft/repair/utils/WEUtils.java
Somewhere in the API here would be a good place to make our data structure.

2021-03-05 23:34 UTC, eirikh1996 commented
Requested changes made @TylerS1066

2021-03-06 02:09 UTC, TylerS1066 approved these changes

2021-03-07 23:16 UTC, merged