Add savedstates command
APDevTeam/Movecraft-Repair pull request #8
Opened 2021-05-18 17:56 UTC by HumorousFool

This adds a command for players to see a list of their own saved states and for admins to see any player's saved states.

This has been compiled and test and has proper internationalization.

I apologize for not opening an issue about this, it has been discussed many times on APDevTeam/Movecraft and I thought an issue for it was open here.

2021-05-18 22:29 UTC, TylerS1066 requested changes

2021-05-18 22:29 UTC, TylerS1066 commented on plugin/src/main/java/net/countercraft/movecraft/repair/commands/SavedStatesCommand.java
> +        if(!sender.hasPermission("movecraftrepair.savedstates")) {
Let's use "movecraft.repair.command.savedstates"

2021-05-18 22:29 UTC, TylerS1066 commented on plugin/src/main/java/net/countercraft/movecraft/repair/commands/SavedStatesCommand.java
> +            else if(sender.hasPermission("movecraftrepair.savedstates.other")) {
Similar here

2021-05-18 22:29 UTC, TylerS1066 commented on plugin/src/main/java/net/countercraft/movecraft/repair/commands/SavedStatesCommand.java
> +                paginator.addLine(file.getName().replace(".schematic", ""));
1.13+ schematics are .schem iirc, which may mean we need to implement some sort of conversion process or update the saving name.

2021-05-18 22:53 UTC, HumorousFool commented
While .schem files are 1.13+ WE's default schematic files Movecraft-Repair still uses .schematic files so I've allowed it to handle both in case we switch. Otherwise, requested changes have been made.

2021-06-06 02:26 UTC, HumorousFool commented
How does this look?

2021-06-06 20:50 UTC, TylerS1066 reviewed
This looks pretty good, I just have a few notes.

I unfortunately do not have a Movecraft 8.0 test server setup yet, so I am unable to test and approve this PR yet.

2021-06-06 20:50 UTC, TylerS1066 commented on plugin/src/main/resources/plugin.yml
> +    default: true
This should be of the form `movecraft.repair.____`.  This should also default to op, let owners decide if they want to add the permission.

2021-06-06 20:50 UTC, TylerS1066 commented on plugin/src/main/resources/plugin.yml
> +    description: Allows you to see the saved states of other players.
This should be of the form `movecraft.repair.____`.  This should also default to op.

2021-06-07 05:19 UTC, HumorousFool commented
Requested changes made

2021-06-07 21:57 UTC, TylerS1066 approved these changes
Looks good!

It's going to be a while until I have a 1.14.4 server setup to test this, but if it works then I'll merge it.

2021-09-29 01:03 UTC, TylerS1066 commented
Just as a heads up, as of https://github.com/APDevTeam/Movecraft-Repair/commit/ad3da4616f14faf38678d5773e20b0ae1d5912d4 there have been some breaking changes to how Movecraft-Repair saves schematics (we now default to the proper .schem extension for sponge format schematics).  In the coming weeks, it's also planned to remove the 6.0 to 7.0 upgrade system and implement a .schematic (MCEdit format) to .schem conversion.

2021-09-29 16:25 UTC, HumorousFool commented
Ok I'll update this when I can

2021-11-18 18:54 UTC, closed without merging